#remote_theme: aspirethemes/type
remote_theme: pmarsceill/just-the-docs

# --- Required options --- #

# Name of website
title: Morbergs receptsamling

# Your name to show in the footer
author: Niklas Morberg

# No point in deep linking within a recipe page
heading_anchors: false